# -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

# def options(opt):
#     pass

# def configure(conf):
#     conf.check_nonfatal(header_name='stdint.h', define_name='HAVE_STDINT_H')

def build(bld):
    module = bld.create_ns3_module('pbs-switch', ['core', 'network'])
    module.source = [
        'model/pbs-switch.cc',
    #    'helper/pbs-switch-helper.cc',
        ]

    module_test = bld.create_ns3_module_test_library('pbs-switch')
    module_test.source = [
    #    'test/pbs-switch-test-suite.cc',
        ]

    headers = bld(features='ns3header')
    headers.module = 'pbs-switch'
    headers.source = [
        'model/pbs-switch.h',
    #    'helper/pbs-switch-helper.h',
        ]

    #if bld.env.ENABLE_EXAMPLES:
    #    bld.recurse('examples')

    # bld.ns3_python_bindings()

